<?php

namespace app\modules\employee\models;

use Yii;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use voskobovich\linker\LinkerBehavior;
use app\modules\directories\models\position\Position;
use app\modules\employee\models\cyclic_commission\CyclicCommission;

use PHPExcel;
use PHPExcel_IOFactory;

/**
 * This is the model class for table "employee".
 * @property integer $id
 * @property integer $is_in_education
 * @property integer $position_id
 * @property integer $category_id
 * @property integer $type
 * @property string $first_name
 * @property string $middle_name
 * @property string $last_name
 * @property integer $gender
 * @property integer $cyclic_commission_id
 * @property string $birth_date
 * @property string $passport
 * @property string $passport_issued_by
 * @property string $passport_issued_date
 * @property string $start_date
 * 
 * @property EmployeeEducation[] $education
 */
class Employee extends ActiveRecord
{
    /** Types */
    const TYPE_NONE = 0;
    const TYPE_TEACHER = 1;
    const TYPE_OTHER = 2;

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * @return string the associated database table name
     */
    public static function tableName()
    {
        return '{{%employee}}';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        return [
            [['id', 'position_id', 'category_id', 'is_in_education', 'gender', 'type', 'cyclic_commission_id'], 'integer'],
            [['last_name', 'first_name', 'middle_name', 'position_id', 'is_in_education',
                'gender', 'passport', 'birth_date', 'passport_issued_by', 'start_date', 'passport_issued_date'], 'required'],
            [['birth_date','cyclic_commission_id', 'passport', 'passport_issued_by'], 'safe'],
            [['passport', 'id'], 'unique'],
        ];
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'is_in_education' => Yii::t('app', 'Do teach?'),
            'position_id' => Yii::t('app', 'Position'),
            'category_id' => Yii::t('app', 'Category'),
            'type' => Yii::t('app', 'Type'),
            'first_name' => Yii::t('app', 'First Name'),
            'middle_name' => Yii::t('app', 'Middle Name'),
            'last_name' => Yii::t('app', 'Last Name'),
            'gender' => Yii::t('app', 'Gender'),
            'cyclic_commission_id' => Yii::t('app', 'Cyclic commission'),
            'birth_date' => Yii::t('app', 'Birth Day'),
            'passport' => Yii::t('app', 'Passport Code'),
            'passport_issued_by' => Yii::t('app', 'Passport issued'),
            'passport_issued_date' => Yii::t('app', 'Passport issued date'),
            'start_date' => Yii::t('app', 'Start date'),
        ];
    }

    public function getFullName()
    {
        return trim("$this->last_name $this->first_name $this->middle_name");
    }

    public function getNameWithInitials()
    {
        $firstNameInitial = mb_substr($this->first_name, 0, 1, 'UTF-8');
        $middleNameInitial = mb_substr($this->middle_name, 0, 1, 'UTF-8');
        return trim("$this->last_name {$firstNameInitial}. {$middleNameInitial}.");
    }

    public function getShortName()
    {
        return $this->first_name . ' ' . $this->middle_name . ' ' . $this->last_name;
    }

    public static function getTypes()
    {
        return [
            self::TYPE_NONE => Yii::t('employee', 'Nobody'),
            self::TYPE_OTHER => Yii::t('employee', 'Another employee'),
            self::TYPE_TEACHER => Yii::t('employee', 'Teacher'),
        ];
    }

    public function getGenderName()
    {
        return $this->gender ? Yii::t('app', 'Female') : Yii::t('app', 'Male');
    }
    
    public function getIsInEducationName()
    {
        return $this->is_in_education ? Yii::t('app', 'Take part in education') : Yii::t('app', 'Not take part in education');
    }

    public static function getList()
    {
        $data = Employee::find()->all();
        $items = ArrayHelper::map($data,'id','nameWithInitials');
        return $items;
    }


    public
    static function getCyclicCommissionArray()
    {
        $array = null;
        foreach ($id as $item) {
            $array[$item->data['current']['cyclic_commission_id']] = $item->data['current']['position_id'];
        }
        return $array;
    }

    public function getEducation()
    {
        return $this->hasMany(EmployeeEducation::className(), ['employee_id' => 'id']);
    }

    public static function createMultiple($modelClass, $multipleModels = [], $pk = 'id')
    {
        $model = new $modelClass;
        $formName = $model->formName();
        $post = Yii::$app->request->post($formName);
        $models = [];

        if (!empty($multipleModels)) {
            $keys = array_keys(ArrayHelper::map($multipleModels, $pk, $pk));
            $multipleModels = array_combine($keys, $multipleModels);
        }

        if ($post && is_array($post)) {
            foreach ($post as $i => $item) {
                if (isset($item[$pk]) && !empty($item[$pk]) && isset($multipleModels[$item[$pk]])) {
                    $models[] = $multipleModels[$item[$pk]];
                } else {
                    $models[] = new $modelClass;
                }
            }
        }
    }

    public function getPosition()
    {
        return Position::findOne(['id' => $this->position_id])->title;
    }

    public  function getCyclicCommission()
    {
        return CyclicCommission::findOne(['id' => $this->cyclic_commission_id])->title;
    }

    public function getEmployeeArray()
    {
        /**
         * @var $result Employee[];
         * @var $employee Employee[];
         */
        $result = [];
        $employee = Employee::find()->all();
                    array_push($result, $employee);

        return $result;
    }

    public function getDocument()
    {
        $tmpfname = Yii::getAlias('@webroot') . "/templates/employee.xls";
        $excelReader = PHPExcel_IOFactory::createReaderForFile($tmpfname);;
        $excelObj = $excelReader->load($tmpfname);
        $excelObj->setActiveSheetIndex(0);

        /**
         * @var Employee[] $employees
         */
        $employees = $this->getEmployeeArray();
        if (!is_null($employees)) {
            $startRow = 4;
            $current = $startRow;
            $i = 1;
            foreach ($employees as $employee) {
                $excelObj->getActiveSheet()->mergeCells("C" . $current . ":D" . $current);
                $excelObj->getActiveSheet()->mergeCells("E" . $current . ":I" . $current);
                $excelObj->getActiveSheet()->mergeCells("J" . $current . ":M" . $current);

                $excelObj->getActiveSheet()->insertNewRowBefore($current + 1);
                $excelObj->getActiveSheet()->setCellValue('B' . $current, $i);
                $excelObj->getActiveSheet()->setCellValue('C' . $current, $employee->getPosition());
                $excelObj->getActiveSheet()->setCellValue('E' . $current, $employee->getFullName());
                $excelObj->getActiveSheet()->setCellValue('G' . $current, $employee->getCyclicCommission());
                $i++;
                $current++;
            }
            $excelObj->getActiveSheet()->removeRow($current);
            $excelObj->getActiveSheet()->removeRow($current);
//            $excelObj->getActiveSheet()
//                ->getCell('C' . $current - 1)
//                ->getStyle()
//                ->getBorders()
//                ->getBottom()
//                ->setBorderStyle(\PHPExcel_Style_Border::BORDER_NONE);
//            $excelObj->getActiveSheet()
//                ->getCell('B' . $current - 1)
//                ->getStyle()
//                ->getBorders()
//                ->getBottom()
//                ->setBorderStyle(\PHPExcel_Style_Border::BORDER_NONE);
//            $excelObj->getActiveSheet()
//                ->getCell('H' . $current - 1)
//                ->getStyle()
//                ->getBorders()
//                ->getBottom()
//                ->setBorderStyle(\PHPExcel_Style_Border::BORDER_NONE);
        }
        header('Content-Type: application/vnd.ms-excel');
        $filename = "Employee_" . $this->title . "_" . date("d-m-Y-His") . ".xls";
        header('Content-Disposition: attachment;filename=' . $filename . ' ');
        header('Cache-Control: max-age=0');
        $objWriter = PHPExcel_IOFactory::createWriter($excelObj, 'Excel2007');
        $objWriter->save('php://output');
    }
    
    

}
