<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Audiences' => '',
    'Directories' => '',
    'Home' => '',
    'Students' => 'Студенти',
    'Student' => 'Студент',
    'Last Name' => 'Прізвище',
    'First Name' => 'Ім\'я',
    'Middle Name' => 'По-батькові',
    'Student Code' => 'Номер студентського',
    'Gender' => 'Стать',
    'Birth Day' => 'Дата народження',
    'Passport Code' => 'Серія та номер паспорта',
    'Tax Code' => 'Реєстраційний номер облікової картки платника податків',
    'Status' => 'Статус в базі',
    'Form of study' => 'Форма навчання',
    'Created At' => 'Додано запис',
    'Updated At' => 'Оновлено',
    'Sseed ID' => 'Ідентифікаційний номер ЄДБО',
    'Fields with <span class="required">*</span> are required.' => 'Поля, відмічені <span class="required">*</span>, обов\'язкові для заповнення.',
    'Female' => 'Жінка',
    'Male' => 'Чоловік',
    'Select gender' => 'Оберіть стать',
    'Are you sure you want to delete this item?' => 'Ви хочете видалити цей елемент?',
    'Update student: ' => 'Оновлення: ',
    'Create Student' => 'Додати студента',
    'Update' => 'Оновити',
    'Delete' => 'Видалити',
    'Create' => 'Створити',
    'Birth Certificate' => 'Свідоцтво про народження',
    'List' => 'Список',
    'Passport issued' => 'Паспорт видано',
    'Photo' => 'Фотографія',
    'Start of the study year' => 'Початок навчального року',
    'End of the study year' => 'Кінець навчального року',
    'Adding new study year' => 'Додати новий навчальний рік',
    'Study years list' => 'Перелік навчальних років',
    'Update study year' => 'Редагувати навчальний рік',
    'Delete study year' => 'Видалити навчальний рік',
    'Passport issued date' => 'Дата видачі паспорта',
    'Family' => 'Сім\'я',
    'Type Family Tie' => 'Тип сімейного зв\'язоку',
    'Add tie' => 'Додати зв\'язок',
    'Phone' => 'Телефон',
    'Work Place' => 'Місце роботи',
    'Work Position' => 'Посада',
    'Email' => 'Email адреса',
    'Family tie' => 'Сімейний зв\'язок',
    'Select' => 'Оберіть',
    'Family tie type' => 'тип сімейного зв\'язку',
    'Family ties types' => 'Типи сімейного зв\'язку',
    'Create Family Ties Type' => 'Створити тип родинного зв\'язку',
    'Family Ties Types' => 'Типи сімейних зв\'язків',
    'Title' => 'Назва',
    'include' => 'Зарахувати',
    'exclude' => 'Відрахувати',
    'Exemptions' => 'Пільги',
    'Create Exemption' => 'Створити пільгу',
    'Update Exemption' => 'Оновити пільгу',
];
