<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Calculation and control works' => '',
    'Consultations' => '',
    'Consultations amount exceeds maximum' => '',
    'Course project' => '',
    'Course work' => '',
    'Diploma project' => '',
    'Load creating' => 'Створення запису про навантаження',
    'Loads' => 'Навантаження',
    'Practice management, diploma control, state qualification commissions' => '',
    'Project type' => '',
    'Select study year' => 'Оберіть навчальний рік',
    'Total students' => '',
    'Total students on budget' => '',
    'Total students on contract' => '',
    '' => '',
    'Create load' => 'Створити навантаження',
    'Load' => 'Навантаження',
    'View loads' => 'Переглянути навантаження',
];
