<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access control' => 'Контроль доступу',
    'Accesses have been updated' => '',
    'Action' => '',
    'Action Access ID' => '',
    'Action Accesses' => 'Контроль дій',
    'Actions access' => 'Контроль дій',
    'Add items to action' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Item Name' => '',
    'Choose action' => '',
    'Choose controller' => '',
    'Choose module' => '',
    'Class' => '',
    'Controller' => '',
    'Create' => '',
    'Create Action Access' => '',
    'Create permission' => '',
    'Create role' => '',
    'Create rule' => '',
    'Created at' => '',
    'Delete' => '',
    'Description' => '',
    'ID' => '',
    'Items' => '',
    'List' => '',
    'Module' => '',
    'Name' => '',
    'Permissions' => '',
    'Roles' => '',
    'Rule name' => '',
    'Rules' => '',
    'Save' => '',
    'Select rule' => '',
    'Update' => '',
    'Update items' => '',
    'Update permission' => '',
    'Update role' => '',
    'Update rule' => '',
    'Update {modelClass}: ' => '',
    'Updated at' => '',
    'You don\'t have permission to' => '',
    'create task for this project' => '',
    'delete this project' => '',
    'delete this task' => '',
    'do this action' => '',
    'update this project' => '',
    'update this task' => '',
];
