<?php

namespace app\modules\directories\models;

use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "speciality".
 *
 * @property integer $id
 * @property string $title
 * @property integer $department_id
 * @property integer $number
 * @property string $accreditation_date
 *
 * @property Department $department
 * @property $specialityQualifications SpecialityQualification[]
 */
class Speciality extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'speciality';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['department_id'], 'integer'],
            [['accreditation_date'], 'safe'],
            [['title', 'number'], 'string', 'max' => 255],
            [['department_id', 'title'], 'required'],
        ];
    }

    /**
     * @inheritdoc
     */

    /**
     * @return int
     */
    public function getDepartment()
    {
        return $this->hasOne(Department::className(), ['id' => 'department_id']);
    }

    public function getSpecialityQualifications()
    {
        return $this->hasMany(SpecialityQualification::className(), ['speciality_id' => 'id']);
    }

    public function getQualification()
    {
        return $this->hasMany(Qualification::className(), ['id' => 'qualification_id'])
            ->via('specialityQualifications');
    }

    public static function getSpecialityTreeList()
    {
        $list = [];


        $department = Department::find()->all();
        foreach ($department as $item) {
            /* @var $item Department */
            $list[$item->title] = [];
            foreach ($item->specialities as $speciality) {
                /**
                 * @var $speciality Speciality
                 */
                $list[$item->title][$speciality->id] = $speciality->title;
            }
        }
        return $list;

    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'department' => 'Department',
            'number' => 'Number',
            'accreditation_date' => 'Accreditation Date',
        ];
    }

    /**
     * @inheritdoc
     * @return SpecialityQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SpecialityQuery(get_called_class());
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            $this->accreditation_date = date('Y-m-d', strtotime($this->accreditation_date));
            return true;
        } else {
            return false;
        }
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->accreditation_date = date('d.m.Y', strtotime($this->accreditation_date));
    }
}
