<?php
/* @author VasyaKog */
namespace app\modules\students\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\console\controllers\HelpController;
use yii\helpers\Html;
use app\modules\students\models\File;
use yii\web\UploadedFile;

/**
 * This is the model class for table "student".
 *
 * @property integer $id
 * @property string $student_code
 * @property integer $sseed_id
 * @property integer $user_id
 * @property string $last_name
 * @property string $first_name
 * @property string $middle_name
 * @property integer $gender
 * @property string $birth_day
 * @property string $passport_code
 * @property string $tax_id
 * @property string $birth_certificate
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $photo
 * @property string $passport_issued
 * @property string $passport_issued_date
 *
 */
class Student extends \yii\db\ActiveRecord
{

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            [
                'class' => '\yiidreamteam\upload\ImageUploadBehavior',
                'attribute' => 'photo',
                'thumbs' => [
                    'thumb' => ['width' => 300, 'height' => 400, 'quality' => 50],
                ],
                'filePath' => '@webroot/uploads/students/photo/[[model]]_[[pk]].[[extension]]',
                'fileUrl' => '/uploads/students/photo/[[model]]_[[pk]].[[extension]]',
                'thumbPath' => '@webroot/uploads/students/photo/[[model]]_[[profile]]_[[pk]].[[extension]]',
                'thumbUrl' => '/uploads/students/photo/[[model]]_[[profile]]_[[pk]].[[extension]]',
            ],
        ]; // TODO: Change the autogenerated stub

    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'student';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sseed_id', 'user_id', 'gender', 'status', 'created_at', 'updated_at'], 'integer'],
            [['last_name', 'first_name', 'middle_name', 'gender'], 'required'],
            [['birth_day', 'passport_issued_date'], 'safe'],
            [['student_code', 'passport_code', 'birth_certificate'], 'string', 'max' => 12],
            [['last_name', 'first_name', 'middle_name', 'passport_issued'], 'string', 'max' => 255],
            [['tax_id'], 'string', 'min' => 10, 'max' => 10],
            [['student_code'], 'unique'],
            [['sseed_id'], 'unique'],
            [['user_id'], 'unique'],
            [['passport_code'], 'unique'],
            [['tax_id'], 'unique'],
            ['photo', 'file', 'extensions' => 'jpeg, jpg, gif, png'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'student_code' => Yii::t('app', 'Student Code'),
            'sseed_id' => Yii::t('app', 'Sseed ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'last_name' => Yii::t('app', 'Last Name'),
            'first_name' => Yii::t('app', 'First Name'),
            'middle_name' => Yii::t('app', 'Middle Name'),
            'gender' => Yii::t('app', 'Gender'),
            'birth_day' => Yii::t('app', 'Birth Day'),
            'passport_code' => Yii::t('app', 'Passport Code'),
            'tax_id' => Yii::t('app', 'Tax Code'),
            'status' => Yii::t('app', 'Status'),
            'birth_certificate' => Yii::t('app', 'Birth Certificate'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'passport_issued' => Yii::t('app', 'Passport issued'),
            'photo' => Yii::t('app', 'Photo'),
            'passport_issued_date' => Yii::t('app', 'Passport issued date'),
        ];
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            $this->birth_day = date('Y-m-d', strtotime($this->birth_day));
            if (is_null(!$this->passport_issued_date)) {
                $this->passport_issued_date = date('Y-m-d', strtotime($this->passport_issued_date));
            }

            return true;
        } else {
            return false;
        }
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->birth_day = date('d.m.Y', strtotime($this->birth_day));
        if (!is_null($this->passport_issued_date)) {
            $this->passport_issued_date = date('d.m.Y', strtotime($this->passport_issued_date));
        }
    }

    public function getGenderName()
    {
        return $this->gender ? Yii::t('app', 'Female') : Yii::t('app', 'Male');
    }

    public function getFullNameAndCode()
    {
        return $this->getFullName() . ' ' . $this->student_code;
    }

    public function getFullName()
    {
        return $this->last_name . ' ' . $this->first_name . ' ' . $this->middle_name;
    }

    public function getShortName()
    {
        return $this->last_name . ' ' . mb_substr($this->first_name, 0, 1, 'UTF-8') . '.' . mb_substr($this->middle_name, 0, 1, 'UTF-8') . '.';
    }

    public function getLink()
    {
        return Html::a($this->getShortName(), ['student/default/view', 'id' => $this->id]);
    }

    public function getPhoto()
    {
        if (!is_null($this->getImageFileUrl('photo'))) {
            return Html::img($this->getImageFileUrl('photo'), ['height' => 200, 'width' => 150]);
        }
        return Yii::t('app', 'Image not set');
    }

    public static function importXml($file)
    {
        /**
         * @var $xml \SimpleXMLElement
         * @var file File;
         */

        $xmlFile = UploadedFile::getInstance($file, 'file');

        $xml = simplexml_load_file($xmlFile->tempName);
        $json = json_encode($xml);
        $array = json_decode($json, TRUE);
        $i = 0;
        foreach ($array['student'] as $item) {
            $student = self::findOne(['sseed_id' => $item['edbo_education_id']]);

            if (is_null($student)) {
                $student = new Student();
            }
            if (!is_null($item['last_name']['@attributes']['uk'])) $student->last_name = $item['last_name']['@attributes']['uk'];
            if (!is_null($item['first_name']['@attributes']['uk'])) $student->first_name = $item['first_name']['@attributes']['uk'];
            if (!is_null($item['middle_name']['@attributes']['uk'])) $student->middle_name = $item['middle_name']['@attributes']['uk'];
            if (!is_null($item['birthday'])) $student->birth_day = $item['birthday'];
            if (!is_null($item['sex'])) $student->gender = $item['sex'];
            if (!is_null($item['ipn'])) $student->tax_id = $item['ipn'];
            if (!is_null($item['person_document']['@attributes']['ID'])) if ($item['person_document']['@attributes']['ID'] == '1') {
                if (!is_null($item['person_document']['@attributes']['seria'])) $student->passport_code = $item['person_document']['@attributes']['seria'] . ' №' . $item['person_document']['@attributes']['number'];
                if (!is_null($item['person_document']['@attributes']['issued_by'])) $student->passport_issued = $item['person_document']['@attributes']['issued_by'];
                if (!is_null($item['person_document']['@attributes']['issued_date'])) $student->passport_issued_date = $item['person_document']['@attributes']['issued_date'];
            } else {
                $student->birth_certificate = $item['person_document']['@attributes']['seria'] . ' №' . $item['person_document']['@attributes']['number'];
            }
            if (!is_null($item['edbo_education_id'])) $student->sseed_id = $item['edbo_education_id'];
            if (!is_null($item['photo'])) $student->photo = $item['photo'];
            var_dump($student);
            $student->save();
            if (!is_null($item['last_name']['@attributes']['uk'])) {
                $path = __DIR__ . "/../../../../web/uploads/students/photo/";
                copy($_FILES['File']['tmp_name']['photos'][$i], $path . 'student_' . $student->id . '.jpeg');
            }
            $i++;
        }
    }

    public function getGroupArray($date = null)
    {
        if ($date == null) {
            $date = date('d.m.y');
        };
        $listRecord = StudentGroup::find()->where(['student_id' => $this->id])->all();
        $listGroup = array();
        // sort($listRecord,1);

        foreach ($listRecord as $item) {

            if ($item->type == 0) {

                if ($date < $item->date) continue;
                $k = 1;
                if (in_array($item->group_id, $listGroup)) continue;
                foreach ($listRecord as $item2) {
                    if ($item2->date > $date) continue;
                    if ($item->group_id == $item2->group_id) {
                        if ($item != $item2 && $item2->type == 1) {
                            $k += 1;
                        }
                    }
                }

                if ($k % 2 != 0) {
                    array_push($listGroup, $item->group_id);
                }
            }
        }
        return $listGroup;
    }

    public function getGroupLinksList()
    {
        $links = "";
        $arr = $this->getGroupArray();
        if (empty($arr)) return Yii::t('app', 'This student has not group');
        foreach ($arr as $item) {
            $group = Group::findOne(['id' => $item]);
            $links .= Html::a($group->title, ['/students/group/view', 'id' => $group->id]);
        }
        return $links;

    }
}
