<?php

namespace app\modules\students\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\modules\students\models\StudentsHistory;

/**
 * StudentsHistorySearch represents the model behind the search form about `app\modules\students\models\StudentsHistory`.
 */
class StudentsHistorySearch extends StudentsHistory
{
    public $studentFullName;

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'student_id', 'speciality_qualification_id'], 'integer'],
            [['date', 'command', 'studentFullName'], 'safe'],
        ];
    }

    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(), ['studentFullName' => Yii::t('app', 'Full name')]); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = StudentsHistory::find();
        $query->from(StudentsHistory::tableName() . ' main');

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        $dataProvider->sort = false;
        $this->load($params);
        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }
        if ($this->studentFullName) {
            $query->leftJoin(Student::tableName() . ' student', '   `main`.`student_id`=`student`.`id`');
            $searchQuery = explode(' ', $this->studentFullName);
            foreach ($searchQuery as $word) {
                $query->andWhere(
                    ['like', 'CONCAT_WS(" ",student.first_name,student.last_name,student.middle_name)', $word]
                );
            }
        }
        return $dataProvider;
    }
}
