<?php
/* @author VasyaKog */
namespace app\modules\students\models;

use nullref\useful\behaviors\RelatedBehavior;
use voskobovich\linker\LinkerBehavior;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\console\controllers\HelpController;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use app\modules\students\models\File;
use yii\web\UploadedFile;

/**
 * This is the model class for table "student".
 *
 * @property integer $id    
 * @property string $student_code
 * @property integer $sseed_id
 * @property integer $user_id
 * @property string $last_name
 * @property string $first_name
 * @property string $middle_name
 * @property integer $gender
 * @property string $birth_day
 * @property string $passport_code
 * @property string $tax_id
 * @property string $birth_certificate
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $photo
 * @property string $passport_issued
 * @property string $passport_issued_date
 *
 *
 * @property FamilyTie[] $family
 * @property Exemption[] $exemptions
 */
class Student extends \yii\db\ActiveRecord
{

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            [
                'class' => '\yiidreamteam\upload\ImageUploadBehavior',
                'attribute' => 'photo',
                'thumbs' => [
                    'thumb' => ['width' => 300, 'height' => 400, 'quality' => 50],
                ],
                'filePath' => '@webroot/uploads/students/photo/[[model]]_[[pk]].[[extension]]',
                'fileUrl' => '/uploads/students/photo/[[model]]_[[pk]].[[extension]]',
                'thumbPath' => '@webroot/uploads/students/photo/[[model]]_[[profile]]_[[pk]].[[extension]]',
                'thumbUrl' => '/uploads/students/photo/[[model]]_[[profile]]_[[pk]].[[extension]]',
            ],
            [
                'class' => LinkerBehavior::className(),
                'relations' => [
                    'exemption_ids' => 'exemptions',
                ],
            ],


        ]; // TODO: Change the autogenerated stub

    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%student}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sseed_id', 'user_id', 'gender', 'status', 'created_at', 'updated_at'], 'integer'],
            [['last_name', 'first_name', 'middle_name', 'gender'], 'required'],
            [['birth_day', 'passport_issued_date'], 'safe'],
            [['exemption_ids'], 'each', 'rule' => ['integer']],
            [['student_code', 'passport_code', 'birth_certificate'], 'string', 'max' => 12],
            [['last_name', 'first_name', 'middle_name', 'passport_issued'], 'string', 'max' => 255],
            [['tax_id'], 'string', 'min' => 10, 'max' => 10],
            [['student_code'], 'unique'],
            [['sseed_id'], 'unique'],
            [['user_id'], 'unique'],
            [['passport_code'], 'unique'],
            [['tax_id'], 'unique'],
            ['photo', 'file', 'extensions' => 'jpeg, jpg, gif, png'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'student_code' => Yii::t('app', 'Student Code'),
            'sseed_id' => Yii::t('app', 'Sseed ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'last_name' => Yii::t('app', 'Last Name'),
            'first_name' => Yii::t('app', 'First Name'),
            'middle_name' => Yii::t('app', 'Middle Name'),
            'gender' => Yii::t('app', 'Gender'),
            'birth_day' => Yii::t('app', 'Birth Day'),
            'passport_code' => Yii::t('app', 'Passport Code'),
            'tax_id' => Yii::t('app', 'Tax Code'),
            'status' => Yii::t('app', 'Status'),
            'birth_certificate' => Yii::t('app', 'Birth Certificate'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'passport_issued' => Yii::t('app', 'Passport issued'),
            'photo' => Yii::t('app', 'Photo'),
            'passport_issued_date' => Yii::t('app', 'Passport issued date'),
            'exemptions' => Yii::t('app', 'Exemptions'),
            'exemption_ids' => Yii::t('app', 'Exemptions'),
        ];
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            $this->birth_day = date('Y-m-d', strtotime($this->birth_day));
            if (is_null(!$this->passport_issued_date)) {
                $this->passport_issued_date = date('Y-m-d', strtotime($this->passport_issued_date));
            }

            return true;
        } else {
            return false;
        }
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->birth_day = date('d.m.Y', strtotime($this->birth_day));
        if (!is_null($this->passport_issued_date)) {
            $this->passport_issued_date = date('d.m.Y', strtotime($this->passport_issued_date));
        }
    }

    public function getGenderName()
    {
        return $this->gender ? Yii::t('app', 'Female') : Yii::t('app', 'Male');
    }

    public function getFullNameAndCode()
    {
        return $this->getFullName() . ' ' . $this->student_code;
    }

    public function getFullName()
    {
        return $this->last_name . ' ' . $this->first_name . ' ' . $this->middle_name;
    }

    public function getShortName()
    {
        return $this->last_name . ' ' . mb_substr($this->first_name, 0, 1, 'UTF-8') . '.' . mb_substr($this->middle_name, 0, 1, 'UTF-8') . '.';
    }

    public function getLink()
    {
        return Html::a($this->getShortName(), ['student/default/view', 'id' => $this->id]);
    }

    public function getPhoto()
    {
        if (!is_null($this->getImageFileUrl('photo'))) {
            return Html::img($this->getImageFileUrl('photo'), ['height' => 200, 'width' => 150]);
        }
        return Yii::t('app', 'Image not set');
    }

    public static function importXml($file)
    {
        /**
         * @var $xml \SimpleXMLElement
         * @var file File;
         */

        $xmlFile = UploadedFile::getInstance($file, 'file');

        $xml = simplexml_load_file($xmlFile->tempName);
        $json = json_encode($xml);
        $array = json_decode($json, TRUE);
        $i = 0;
        foreach ($array['student'] as $item) {
            $student = self::findOne(['sseed_id' => $item['edbo_education_id']]);

            if (is_null($student)) {
                $student = new Student();
            }
            if (!is_null($item['last_name']['@attributes']['uk'])) $student->last_name = $item['last_name']['@attributes']['uk'];
            if (!is_null($item['first_name']['@attributes']['uk'])) $student->first_name = $item['first_name']['@attributes']['uk'];
            if (!is_null($item['middle_name']['@attributes']['uk'])) $student->middle_name = $item['middle_name']['@attributes']['uk'];
            if (!is_null($item['birthday'])) $student->birth_day = $item['birthday'];
            if (!is_null($item['sex'])) $student->gender = $item['sex'];
            if (!is_null($item['ipn'])) $student->tax_id = $item['ipn'];
            if (!is_null($item['person_document']['@attributes']['ID'])) if ($item['person_document']['@attributes']['ID'] == '1') {
                if (!is_null($item['person_document']['@attributes']['seria'])) $student->passport_code = $item['person_document']['@attributes']['seria'] . ' №' . $item['person_document']['@attributes']['number'];
                if (!is_null($item['person_document']['@attributes']['issued_by'])) $student->passport_issued = $item['person_document']['@attributes']['issued_by'];
                if (!is_null($item['person_document']['@attributes']['issued_date'])) $student->passport_issued_date = $item['person_document']['@attributes']['issued_date'];
            } else {
                $student->birth_certificate = $item['person_document']['@attributes']['seria'] . ' №' . $item['person_document']['@attributes']['number'];
            }
            if (!is_null($item['edbo_education_id'])) $student->sseed_id = $item['edbo_education_id'];
            if (!is_null($item['photo'])) $student->photo = $item['photo'];
            $student->save();
            if (!is_null($item['last_name']['@attributes']['uk'])) {
                $path = __DIR__ . "/../../../../web/uploads/students/photo/";
                copy($_FILES['File']['tmp_name']['photos'][$i], $path . 'student_' . $student->id . '.jpeg');
            }
            $i++;
        }
    }

    public function getGroupLinksList()
    {
        $groups = $this->groups;
        if (empty($groups)) return Yii::t('app', 'This student has not group');
        $links = "";
        foreach ($groups as $item) {
            $links .= Html::a($item->title, ['/students/group/view', 'id' => $item->id]);
        }
        return $links;

    }

    public function getFamily()
    {
        return $this->hasMany(FamilyTie::className(), ['student_id' => 'id']);
    }

    public function getGroupArray()
    {
        return StudentsHistory::getGroupArray($this->id);
    }

    public function getAlumnusGroupArray()
    {
        return StudentsHistory::getAlumnusGroupArray($this->id);
    }


    public function getGroups()
    {
        return Group::find()->where(['id' => $this->getGroupArray()])->all();
    }

    public function getAlumnusGroup()
    {
        return Group::find()->where(['id' => $this->getAlumnusGroupArray()])->all();
    }


    public function getExemptions()
    {
        return $this->hasMany(Exemption::className(), ['id' => 'exemption_id'])->viaTable('{{%exemptions_students_relations}}', ['student_id' => 'id']);
    }

    public static function getList()
    {
        $models = self::find()->all();
        return ArrayHelper::map($models, 'id', 'fullNameAndCode');
    }

    public static function createMultiple($modelClass, $multipleModels = [], $pk = 'id')
    {
        $model = new $modelClass;
        $formName = $model->formName();
        $post = Yii::$app->request->post($formName);
        $models = [];

        if (!empty($multipleModels)) {
            $keys = array_keys(ArrayHelper::map($multipleModels, $pk, $pk));
            $multipleModels = array_combine($keys, $multipleModels);
        }

        if ($post && is_array($post)) {
            foreach ($post as $i => $item) {
                if (isset($item[$pk]) && !empty($item[$pk]) && isset($multipleModels[$item[$pk]])) {
                    $models[] = $multipleModels[$item[$pk]];
                } else {
                    $models[] = new $modelClass;
                }
            }
        }

        unset($model, $formName, $post);

        return $models;
    }


    /**
     * @return ActiveQuery
     */
    public static function find()
    {
        return parent::find()->addOrderBy(['last_name' => SORT_ASC, 'first_name' => SORT_ASC, 'middle_name' => SORT_ASC]); // TODO: Change the autogenerated stub
    }
}
